name: format_date_x
description: >-
  Convert and format dates easily in Dart/Flutter. Supports ISO, US, EU,
  custom formats, string extensions, and optional BLoC integration.
version: 1.0.1
homepage: https://github.com/Hetvikakkad/format_date_x
repository: https://github.com/Hetvikakkad/format_date_x
issue_tracker: https://github.com/Hetvikakkad/format_date_x/issues
documentation: https://github.com/Hetvikakkad/format_date_x#readme

license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: '>=0.18.0 <0.21.0'
  bloc: ^8.1.2

dev_dependencies:
  test: ^1.24.0
  bloc_test: ^9.1.4
  lints: ^3.0.0

topics:
  - date
  - datetime
  - formatting
  - intl
  - bloc
